server {
    listen 4200;
    server_name localhost;
    include /etc/nginx/mime.types;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/v1/auth {
        proxy_pass http://localhost:8080/api/v1/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/productos {
        proxy_pass http://localhost:8081/api/productos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/carrito {
        proxy_pass http://localhost:8082/api/carrito;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
